### PR TITLE
Custom Enumerable Methods Pull Request

### PR DESCRIPTION
**Pull request by temesghentekeste**
In this project, we created a branch called my-enumerables-dev and started developing the project in collaboration. To separate the concerns of our project, we created two files: main.rb and my_enumerables.rb. Rubocop and Gitfllow were used as a linter and git-flow mechanism respectively. 

The following built-in ruby methods from the Enumerable module are included.

- my_each
- my_each_with_index
- my_select
- my_all?
- my_any
- my_none?
- my_count
- my_map
- my_inject

Kindly request a pull request for our project before we merge it into the master branch. Thanks in advance.

### CODE REVIEW

**Comment by davidmrtz-dev** [comment]
## Hi Team.
### Very good job so far.
However, you are not following the GitFlow, as shown in the image below, you are creating the feature branch directly from the master branch and not from a development branch. 👨‍💻  ⬇️ 

Screen Shot 2020-06-18 at 8 19 43 PM


Please, check this step from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/).

****
**Please make the changes required and submit for review once you are ready!** 
****
## Status: Invalid. ⚠️ 
****


**[TSE:  David Elí]** 
Slack: @ David Eli Martinez Garcia

**Comment by ElijahTobs** [comment]
We followed the Git-Flow process and developed our project in the feature branch (my-enumerables-dev) and now, we ask for a new code review.

**Comment by ElijahTobs** [comment]
Thank you for your feedback @davitomix

**Review by rOluochKe — APPROVED** [review]
Hello @temesghentekeste and @ElijahTobs 
### You have done a good job in this project :clap: All the methods pass the tests. Therefore, the project has been approved. Congratulations :boom: :100:
### You can merge and submit a project completion form from the dashboard. Good luck with the next project.
- Happy coding!

**Pull request merged**
